export const COUNT_INCREMENT="ADD"
export const COUNT_DECREMENT="SUBSTRACT"
export const COUNT_MULTYPLY_X="MULTYPLY_X"
export const COUNT_DIVISION_X="DIVISION_X"
export const COUNT_INCREAMENT_X="INCREAMENT_X"
export const COUNT_DECREMENT_X="DECREMENT_X"
export const INPUT="INPUT"
// export const COUNT_=""
